# Generated by Django 4.2.8 on 2024-02-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cover_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbKey', models.CharField(max_length=30)),
                ('joinDate', models.IntegerField()),
                ('account_playstation', models.CharField(max_length=50, unique=True)),
                ('account_xbox', models.CharField(max_length=50, unique=True)),
                ('account_steam', models.CharField(max_length=50, unique=True)),
                ('account_discord', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
