# Generated by Django 4.2.8 on 2024-02-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fbKey', models.CharField(max_length=30)),
                ('joinDate', models.IntegerField()),
                ('account_playstation', models.CharField(max_length=50, unique=True)),
                ('account_xbox', models.CharField(max_length=50, unique=True)),
                ('account_steam', models.CharField(max_length=50, unique=True)),
                ('account_discord', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
