# Generated by Django 4.2.8 on 2024-02-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partyupapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LFGPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('needed_players', models.IntegerField()),
                ('skill_level', models.CharField(max_length=20)),
                ('platform', models.TextField()),
                ('region', models.TextField()),
                ('mic_needed', models.BooleanField()),
                ('status', models.BooleanField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partyupapi.games')),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partyupapi.user')),
            ],
        ),
    ]
