# Generated by Django 4.2.8 on 2024-02-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyupapi', '0002_lfgpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfgpost',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
