# Generated by Django 4.2.8 on 2024-02-21 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partyupapi', '0003_lfgpost_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='LFGGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partyupapi.lfgpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partyupapi.user')),
            ],
        ),
    ]
