# Generated by Django 4.2.8 on 2024-02-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyupapi', '0004_lfggroupmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
