# Generated by Django 4.2.8 on 2024-02-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyupapi', '0005_alter_games_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lfgpost',
            name='timestamp',
            field=models.DateField(default=0),
        ),
    ]
