# Generated by Django 4.2.8 on 2024-02-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyupapi', '0006_alter_lfgpost_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lfgpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
