# Generated by Django 4.2.8 on 2024-02-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partyupapi', '0008_user_email_address_user_username_alter_user_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_discord',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_playstation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_steam',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_xbox',
            field=models.CharField(max_length=50),
        ),
    ]
